#!/bin/bash


# this needs some xdotool key names that i don't know of... i need the name of this ';' then i'll do shit+; to give :... then w... then enter... but also esc everything.... and then bind tis to capslock + w 
